### ISSUE TITLE
Generating new Hyperdrive has error.

### ISSUE THREAD

**Issue by akachi1409** [holepunchto/hyperdrive-next#33]
I tried the sample code from the document and it has the error.

This is the code section.

```
const Hyperdrive = require('hyperdrive');
const Corestore = require('corestore');

const fs = require('fs');
const corestore = new Corestore('./storage');

const drive = new Hyperdrive(corestore);
```

But when I run` node index.js`, there is this error.
`TypeError [ERR_INVALID_ARG_TYPE]: The "size" argument must be of type number. Received undefined`

Let me know how to resolve this, thank you.

**Comment by mafintosh** [comment]
I don't think you are using the @next package, are you?

**Comment by akachi1409** [comment]
You mean hyperdriver@next package?

**Comment by mafintosh** [comment]
hyperdrive@next yea, ie

`npm install hyperdrive@next`
